version: "3.8"

networks:
  mongodb-network:
    driver: "bridge"

  redis-network:
    driver: "bridge"

services:
  mongodb:
    image: "mongo:7.0.5"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - mongodb-network
    volumes:
      - "~/Documents/projects/data-storage/mongodb:/data/db"

  redis:
    image: "redis:7.2.4"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - "~/Documents/projects/data-storage/redis:/data"
